### PR TITLE
Add Support for OpenTelemetry

### PR DESCRIPTION
**Pull request by atsushii**
Addresses #31 

What I did

Added support for OpenTelemetry (https://opentelemetry.io/docs/instrumentation/go/getting-started/)

Please check the browser data on Jaeger

step

1, mage run
2, send a request e.g. curl http://localhost:8080/health
3, open the Jaeger UI (http://localhost:16686/)

### CODE REVIEW

**Comment by decentralgabe** [comment]
Thank you @atsushii for your contribution. I sent a number of requests to the service while jager was running, but wasn't able to see the traces come through. I'm not familiar with OpenTelemetry so won't be of much use to you here.

Before merging, I think it's valuable to see traces for all requests that come into the service.

In this UI, I see only the jager service show up:
Screen Shot 2022-07-19 at 2 53 49 PM

**Comment by atsushii** [comment]
@decentralgabe 
Did you reload the browser after sending the request? (I missed telling it..)
After reloading the browser, you can see the service like below!

Screen Shot 2022-07-20 at 9 07 44 AM

**Comment by decentralgabe** [comment]
@atsushii I've tried reloading the browser. I even tried using multiple browsers (Safari, Chrome) after sending requests. Still don't see the SSI service show up.

**Comment by atsushii** [comment]
@decentralgabe 
Thank you for trying!

I've deleted containers, images, and volumes before starting a new container then still it works.
I am not really sure why you can not see the SSI service but can you plz try to rebuild the container after deleting all related images, containers, and volumes if it is possible.😅

**Comment by decentralgabe** [comment]
Removed all containers and did a fresh checkout. Worked!

**Review by decentralgabe — APPROVED** [review]

**Pull request merged**
