### PR TITLE
address potential memory issues in Redis readAll function

### PR DESCRIPTION
**Pull request by radurobot**
# Overview
This PR addresses a potential memory issue in the `readAll` function. The function was originally designed to retrieve all keys at once, which could potentially lead to out-of-memory errors for large numbers of keys. Issue: #525 

# Description
The `readAll` function has been revised to use a goroutine and a channel to process each key-value pair individually, which should mitigate the risk of running out of memory. The function ranges over the channel to process each key-value pair and add it to the result map. This approach should be more memory-efficient than the original function, while still only making a single round-trip call to the Redis server.

# How Has This Been Tested?
The function's output and overall logic remain the same, and it has been tested to ensure it still works as expected. Further testing and review are welcome.

# Checklist

Before submitting this PR, please make sure:

- [x] I have read the CONTRIBUTING document.
- [X] My code is consistent with the rest of the project 
- [X] I have tagged the relevant reviewers and/or interested parties
- [X] I have updated the READMEs and other documentation of affected packages

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]
thanks for your contribution! 

will wait for @andresuribe87 to merge

**Comment by andresuribe87** [comment]
Thanks @radurobot for your contribution!

 #525 refers to [this line](https://github.com/TBD54566975/ssi-service/blob/c8541a8597ab1cd8ad1d650d7d682f58e5119ad5/pkg/storage/redis.go#L306). Upon first review, I'm unsure how this PR would address that. Could you clarify what would happen if the DB returns more objects that would not fit in the physical memory of the ssi-service instance?

**Comment by andresuribe87** [comment]
@radurobot that's an awesome solution! But I worry it might just be overcomplicating the problem. I was thinking of something simpler, like returning an error when `readAll` is called with more than 1 Million keys (or similar).

For the full fledged solution, this would involve making sure the most List* endpoints are supporting pagination.

**Comment by andresuribe87** [comment]
> What do you think?

Pagination on List* endpoint is my preferred way to move forward. Some of the benefits include:
* It's a well known pattern. 
* We don't run the risk of OOM when the the collection has too many element.
* It prevents developers from shooting themselves in the foot accidentally, by calling `readAll` on collections that are more than a predefined amount.

**Pull request closed without merging**
