### PR TITLE
Issue #78: Add Linux installation instructions for Go and Mage

### PR DESCRIPTION
**Pull request by ALRubinger**

### CODE REVIEW

**Review by decentralgabe — CHANGES_REQUESTED** [review]
I actually don't think it's worth having multi-platform instructions for a dependency (Mage), since Mage's own documentation covers this. Perhaps this PR can be amended to remove the MacOS specific instructions and just point to the Mage documentation.

**Comment by ALRubinger** [comment]
Yup I think that's all it does -- links to Mage and shows Linux folks that's what they should use. I ported it from the updates I made to the template repo.

**Comment by decentralgabe** [comment]
> Yup I think that's all it does -- links to Mage and shows Linux folks that's what they should use. I ported it from the updates I made to the template repo.

I mean having "MacOS" or "Linux" sections is unnecessary in itself. The tools themselves are multi-platform, and have supporting documentation for specific platforms, so pointing to them without calling out each is sufficient.

**Comment by ALRubinger** [comment]
Oh, could be! I can alter the Mage section here and in the template repo to be "Multi-platform" instead of "macOS"-specific.

**Comment by decentralgabe** [comment]
Fixed in the latest commit https://github.com/TBD54566975/ssi-service/commit/e0e2f33d36fc21b2ecf3746eda3638f8b3281664

If there are specific OS commands worth adding, we can amend. If we're just pointing to mage/go docs - that's covered.

**Pull request closed without merging**
