### PR TITLE
Make storage more friendly.

### PR DESCRIPTION
**Pull request by suutaku**
# Overview
this basically same with #188 

# Description
merge changes by myself;

# How Has This Been Tested?
modified test code with setupTestDB, but still have some internet issue.

# Checklist

Before submitting this PR, please make sure:

- [x] I have read the CONTRIBUTING document.
- [x] My code is consistent with the rest of the project 
- [x] I have tagged the relevant reviewers and/or interested parties
- [x] I have updated the READMEs and other documentation of affected packages

### CODE REVIEW

**Review by andresuribe87 — APPROVED** [review]
Yuck to all the merge conflicts - but this looks good to me. One pending item: make the `service/presentation` folder a more consistent with the rest, but keep the `presentation/submission` hierarchy.

**Comment by andresuribe87** [comment]
I merged before more conflicts happen, since this touches so many files.

**Comment by decentralgabe** [comment]
thank you @suutaku for your work!

**Comment by suutaku** [comment]
Thanks!!

**Pull request merged**
